---
- name: Install ELK Dependencies
  apt:
    name:
      - openjdk-11-jdk
      - apt-transport-https
      - curl
      - gpgv
      - gpgsm
      - gnupg-l10n
      - gnupg
      - dirmngr
    state: latest
    update_cache: true
    
- name: Add GPG Key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Get APT Transport https
  apt: 
    name: apt-transport-https
    state: present

- name: Add Source
  shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: latest
    update_cache: yes
    
- name: Configure Elasticsearch change cluster name
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "cluster.name: demo-elk"
    state: present

- name: Configure Elasticsearch give cluster descriptive name
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "node.name: elk-1"
    state: present

- name: Configure Elasticsearch Add network.host
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "network.host: 0.0.0.0"
    state: present

- name: Configure Elasticsearch Add http.port
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "http.port: 9200"
    state: present

- name: Configure Elasticsearch Add discovery.type
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "discovery.type: single-node"
    state: present

- name: Creating an empty file for startup-timeout.conf 1 of 2
  file:
    path: "/etc/systemd/system/elasticsearch.service.d"
    state: directory

- name: Creating an empty file for startup-timeout.conf 2 of 2
  file:
    path: "/etc/systemd/system/elasticsearch.service.d/startup-timeout.conf"
    state: touch

- name: Prevent systemd service start operation from timing out 
  copy:
    dest: "/etc/systemd/system/elasticsearch.service.d/startup-timeout.conf"
    content: |
      [Service]
      TimeoutStartSec=3min

- name: Run daemon-reload for elasticsearch
  systemd: daemon_reload=yes

- name: Enable service Elasticsearch and ensure it is not masked
  systemd:
    name: elasticsearch
    enabled: yes
    masked: no

- name: ensure elasticsearch is running 
  systemd: state=started name=elasticsearch

- name: Install Kibana
  apt: 
    name: kibana
    state: latest
    update_cache: yes

- name: Configure Kibana Add server.port
  lineinfile:
    dest: /etc/kibana/kibana.yml
    line: "server.port: 5601"
    state: present

- name: Configure Kibana Add server.host
  lineinfile:
    dest: /etc/kibana/kibana.yml
    line: 'server.host: "0.0.0.0"'
    state: present

- name: Configure Kibana Add server.name
  lineinfile:   
    dest: /etc/kibana/kibana.yml
    line: 'server.name: "demo-kibana"'
    state: present

- name: Configure Kibana Add elasticsearch.hosts
  lineinfile:
    dest: /etc/kibana/kibana.yml
    line: 'elasticsearch.hosts: ["http://0.0.0.0:9200"]'

- name: Run daemon-reload for kibana
  systemd: daemon-reload=yes

- name: Enable service Kibana
  systemd:
    name: kibana
    enabled: yes

- name: Start Elasticsearch & Kibana
  shell: systemctl start elasticsearch && systemctl start kibana

- name: Install Logstash
  apt: 
    name: logstash
    state: latest
    update_cache: yes

- name: Run daemon-reload for logstash
  systemd: 
    name: logstash
    enabled: yes

- name: ensure logstash is running 
  systemd: state=started name=logstash

# tasks file for ELK
