---
- name: Creating empty grafana.repo file
  file:
    path: "/etc/yum.repos.d/grafana.repo"
    state: touch

- name: Adding Grafana Repository
  copy:
    dest: /etc/yum.repos.d/grafana.repo
    content: |
      [grafana]
      name=grafana
      baseurl=https://packages.grafana.com/oss/rpm
      repo_gpgcheck=1
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.grafana.com/gpg.key
      sslverify=1
      sslcacert=/etc/pki/tls/certs/ca-bundle.crt

- name: Install Grafana
  yum:
    name: grafana
    state: latest
    update_cache: yes

- name: Start Grafana
  service:
    name: grafana-server
    state: started

- name: Creating empty prometheus.repo file
  file:
    path: "/etc/yum.repos.d/prometheus.repo"
    state: touch

- name: Add Prometheus Repository
  copy:
    dest: /etc/yum.repos.d/prometheus.repo
    content: |
      [prometheus]
      name=prometheus
      baseurl=https://packagecloud.io/prometheus-rpm/release/el/$releasever/$basearch
      repo_gpgcheck=1
      enabled=1
      gpgkey=https://packagecloud.io/prometheus-rpm/release/gpgkey
             https://raw.githubusercontent.com/lest/prometheus-rpm/master/RPM-GPG-KEY-prometheus-rpm
      gpgcheck=1
      metadata_expire=300

- name: Install Prometheus
  yum:
    name: prometheus2
    state: latest
    update_cache: yes

- name: Start Prometheus
  service:
    name: prometheus
    state: started 

- name: Creating empty influxdb.repo file
  file:
    path: "/etc/yum.repos.d/influxdb.repo"
    state: touch

- name: Add Influxdb Repository
  copy:
    dest: /etc/yum.repos.d/influxdb.repo
    content: |
      [influxdb]
      name = influxDB Repository - RHEL
      baseurl = https://repos.influxdata.com/rhel/7/x86_64/stable/
      enabled = 1
      gpgcheck = 1
      gpgkey = https://repos.influxdata.com/influxdb.key

- name: Install Influxdb
  yum:
    name: influxdb
    state: latest
    update_cache: yes

- name: Start Influxdb
  service:
    name: influxdb
    state: started

# tasks file for Grafana
