---
- name: Install httpd
  dnf:
    name: httpd
    state: latest
    update_cache: yes

- name: Add httpd HTML File
  copy:
    content: "Welcome to Apache"
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  register: httpd

- name: Start httpd
  service:
    name: httpd
    state: started
  when: httpd.changed

- name: Stop firewall
  service:
    name: firewalld
    state: stopped

- name: Install MariaDB
  dnf:
    name: mariadb-server
    state: latest
    update_cache: yes

- name: Add MySQL HTML File
  copy:
    content: "Welcome to MySQL"
    dest: /var/www/html/index1.html
    owner: root
    group: root
    mode: '0644'
  register: mysql

- name: Start MariaDB
  service:
    name: mariadb
    state: started
  when: mysql.changed

- name: Install PHP
  dnf:
    name:
      - php 
      - php-mysqlnd
    state: latest
    update_cache: yes

- name: Add PHP HTML File
  copy:
    content: "Welcome to PHP"
    dest: /var/www/html/index2.html
    owner: root
    group: root
    mode: '0644'
  register: php

- name: Restart httpd
  service:
    state: restarted
  when: php.changed

# tasks file for Lamp
